- defaults:
    link:
      relink: true

- clean: ['~', '~/.oh-my-zsh/custom/', '~/.oh-my-zsh/custom/plugins/']

- shell:
  - [sh install_prep.sh, Running pre installation script]
  - [mkdir -p ~/.oh-my-zsh/custom/, Creating oh-my-zsh custom forlders]
  - [mkdir -p ~/.oh-my-zsh/custom/plugins, Creating oh-my-zsh custom plugins forlders]

- link:
    ~/.bashrc: bashrc
    ~/.zshrc: zshrc
    ~/.aliases: aliases

    ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions: oh-my-zsh/custom/plugins/zsh-autosuggestions/
    ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions: oh-my-zsh/custom/plugins/zsh-autosuggestions/
    ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting: oh-my-zsh/custom/plugins/zsh-syntax-highlighting/
    
    # Git
    ~/.gitconfig: git/.gitconfig
    ~/.gitignore: git/.gitignore

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - command: ./run-ansible.sh
      stdin: true
      stdout: true
      description: Pouring software
