---
  - name: Add required homebrew repos
    homebrew_tap:
      name: homebrew/cask-fonts

  - name: Ensure console utils are installed
    homebrew:
      name:
        - bash-completion
        - bat
        - dive
        - exa
        - ffmpeg
        - gh
        - git
        - mc
        - mtr
        - nmap
        - youtube-dl
        - zsh-syntax-highlighting

  - name: apps for life
    homebrew_cask:
      name:
        - deepl
        - discord
        - firefox
        - foxitreader
        - notion
        - obsidian
        - protonvpn
        - spotify
        - zoom
        - google-chrome
        - google-drive
        - iterm2
        - logi-options-plus

  - name: apps for macos
    homebrew_cask:
      name:
        - alt-tab
        - amitv87-pip
        - bartender
        - font-sauce-code-pro-nerd-font
        - kap
        - kap
        - keycastr
        - maccy
        - openin
        - rectangle
        - shottr
        - the-unarchiver
        - vlc

  
  - name: Reduce macos noise
    osx_defaults:
      key: "{{ item.key }}"
      domain: "{{ item.domain }}"
      value: "{{ item.value }}"
    loop:
      - domain: com.apple.dock
        key: no-bouncing
        value: TRUE
