---
  - name: Add required homebrew repos
    homebrew_tap:
      name: homebrew/cask-fonts

  - name: Ensure console utils are installed
    homebrew:
      name:
        - bash-completion
        - bat
        - catimg
        - dive
        - ffmpeg
        - jq
        - gh
        - git
        - gping
        - mas
        - micro
        - mc
        - mtr
        - nmap
        - tree
        - yt-dlp
        - zsh
        - zsh-syntax-highlighting

  - name: apps for life
    homebrew_cask:
      name:
        - 1password
        - anki
        - deepl
        - discord
        - firefox
        - flux-app
        - font-consolas-for-powerline
        - font-fira-code
        - fork
        - google-chrome
        - google-drive
        - iterm2
        - obs
        - obsidian
        - protonvpn
        - sublime-text
        - todoist
        - visual-studio-code
        - vlc
        - zoom

  - name: apps for life o-quarantine
    homebrew_cask:
      name:
        - tomatobar
      install_options:
        - no-quarantine