---
  - name: Add required homebrew repos
    homebrew_tap:
      name: homebrew/cask-fonts

  - name: Ensure console utils are installed
    homebrew:
      name:
        - bash-completion
        - bat
        - dive
        - ffmpeg
        - gh
        - git
        - mc
        - mtr
        - nmap
        - youtube-dl
        - zsh-syntax-highlighting

  - name: apps for life
    homebrew_cask:
      name:
        - 1password
        - anki
        - deepl
        - discord
        - firefox
        - foxitreader
        - fork
        - google-chrome
        - google-drive
        - iterm2
        - notion
        - obsidian
        - protonvpn
        - visual-studio-code
        - zoom

  - name: apps for life o-quarantine
    homebrew_cask:
      name:
        - tomatobar
      install_options:
        - no-quarantine