---
  - name: Ensure console utils are installed
    homebrew:
      name:
        - bash-completion
        - bat
        - catimg
        - dive
        - ffmpeg
        - jq
        - git
        - gping
        - mas
        - micro
        - mc
        - mtr
        - nmap
        - tree
        - yt-dlp
        - zsh
        - zsh-syntax-highlighting

  - name: apps for life
    homebrew_cask:
      name:
        - 1password
        - anki
        - chatgpt
        - deepl
        - discord
        - firefox
        - flux-app
        - fork
        - gimp
        - google-chrome
        - google-drive
        - iterm2
        - obs
        - obsidian
        - protonvpn
        - sublime-text
        - todoist
        - vlc
        - whatsapp
        - zoom

  - name: apps for life o-quarantine
    homebrew_cask:
      name:
        - tomatobar
      install_options:
        - no-quarantine