---
  - name: Add required homebrew repos
    homebrew_tap:
      name: homebrew/cask-fonts

  - name: apps for macos
    homebrew_cask:
      name:
        - iterm2
        - alt-tab
        - amitv87-pip
        - bartender
        - firefox
        - font-jetbrains-mono
        - font-sauce-code-pro-nerd-font
        - google-chrome
        - google-drive
        - ilya-birman-typography-layout
        - kap
        - karabiner-elements
        - keycastr
        - maccy
        - raycast
        - rectangle
        - shottr
        - the-unarchiver
        - vlc
  
  - name: Reduce macos noise
    osx_defaults:
      key: "{{ item.key }}"
      domain: "{{ item.domain }}"
      value: "{{ item.value }}"
    loop:
      - domain: com.apple.dock
        key: no-bouncing
        value: TRUE
