---
  - name: Add required homebrew repos
    homebrew_tap:
      name: homebrew/cask-fonts

  - name: fonts
    homebrew_cask:
      name:
        - font-cascadia-code
        - font-consolas-for-powerline
        - font-fira-code
        - font-jetbrains-mono
        - font-martian-mono
        - font-roboto-mono
        - font-sauce-code-pro-nerd-font

  - name: Ensure console utils are installed
    homebrew:
      name:
        - koekeishiya/formulae/skhd
  
  - name: quick preview plugins
    homebrew:
      name:
        - qlstephen
        - qlmarkdown
        - quicklook-json

  - name: Start skhd service
    shell: skhd --start-service
    become: false

  - name: apps for macos
    homebrew_cask:
      name:
        - alt-tab
        - aldente
        - amitv87-pip
        - jordanbaird-ice
        - firefox
        - google-chrome
        - ilya-birman-typography-layout
        - iterm2
        - kap
        - karabiner-elements
        - losslesscut
        - mas
        - maccy
        - raycast
        - rectangle
        - shottr
        - the-unarchiver
        - keka
        - vlc
  
  - name: Reduce macos noise
    osx_defaults:
      key: "{{ item.key }}"
      domain: "{{ item.domain }}"
      value: "{{ item.value }}"
    loop:
      - domain: com.apple.dock
        key: no-bouncing
        value: TRUE
