---
  - name: Ensure console utils are installed
    homebrew:
      name:
        - ansible-lint
        - bash-completion
        - bat
        - dive
        - git
        - httpie
        - jq
        - mc
        - mtr
        - nmap
        - node
        - python3
        - pyenv
        - zsh-syntax-highlighting

  - name: apps for work
    homebrew_cask:
      name:
        - 1password
        - 1password-cli
        - cursor
        - dbeaver-community
        - fork
        - google-chrome
        - google-cloud-sdk
        - google-drive
        - iterm2
        - keka
        - slack
        - visual-studio-code

  - name: Ensure python and node version managers are installed
    homebrew:
      name:
        - pyenv
        - n
