---
  - name: Add required homebrew repos
    homebrew_tap:
      name: homebrew/cask-fonts

  - name: Ensure console utils are installed
    homebrew:
      name:
        - ansible-lint
        - bash-completion
        - bat
        - dive
        - exa
        - gh
        - git
        - httpie
        - jq
        - mc
        - mtr
        - nmap
        - node
        - python3
        - zsh-syntax-highlighting

  - name: apps for work
    homebrew_cask:
      name:
        - dbeaver-community
        - fork
        - google-chrome
        - google-cloud-sdk
        - google-drive
        - iterm2
        - slack
        - visual-studio-code
        - font-jetbrains-mono

  - name: Ensure python and node version managers are installed
    homebrew:
      name:
        - pyenv
        - n
