---
  - name: Add required homebrew repos
    homebrew_tap:
      name: homebrew/cask-fonts

  - name: Ensure console utils are installed
    homebrew:
      name:
        - ansible-lint
        - bash-completion
        - bat
        - dive
        - exa
        - ffmpeg
        - gh
        - git
        - httpie
        - jq
        - mc
        - mtr
        - nmap
        - node
        - python3
        - youtube-dl

  - name: apps for work
    homebrew_cask:
      name:
        - dbeaver-community
        - fork
        - google-chrome
        - google-cloud-sdk
        - google-drive
        - iterm2
        - slack
        - visual-studio-code

  - name: apps for life
    homebrew_cask:
      name:
        - deepl
        - discord
        - firefox
        - notion
        - obsidian
        - protonvpn
        - spotify
        - zoom

  - name: apps for macos
    homebrew_cask:
      name:
        - alt-tab
        - amitv87-pip
        - bartender
        - font-sauce-code-pro-nerd-font
        - kap
        - kap
        - keycastr
        - maccy
        - rectangle
        - shottr
        - the-unarchiver
        - vlc

  - name: Ensure python and node version managers are installed
    homebrew:
      name:
        - pyenv
        - n
  
  - name: Reduce macos noise
    osx_defaults:
      key: "{{ item.key }}"
      domain: "{{ item.domain }}"
      value: "{{ item.value }}"
    loop:
      - domain: com.apple.dock
        key: no-bouncing
        value: TRUE
